# Generated by Django 4.1.3 on 2022-11-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='../static/img/no-user.jpg', upload_to='upload/'),
        ),
    ]
